In [104]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sb

In [105]:
crdata = pd.read_csv(r"C:\Users\sabar\OneDrive\Documents\AI_ML\Credit Risk Analytics\Risk Dataset\credit_risk_dataset.csv")

In [106]:
crdata.shape

(32581, 12)

In [107]:
crdata_copy = crdata.copy()

In [108]:
crdata_copy.shape

(32581, 12)

In [109]:
crdata.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [110]:
missing_data = crdata.isnull().sum()
missing_data_pct = (missing_data/len(crdata))*100

In [111]:
missing_data_pct.round(2)

person_age                    0.00
person_income                 0.00
person_home_ownership         0.00
person_emp_length             2.75
loan_intent                   0.00
loan_grade                    0.00
loan_amnt                     0.00
loan_int_rate                 9.56
loan_status                   0.00
loan_percent_income           0.00
cb_person_default_on_file     0.00
cb_person_cred_hist_length    0.00
dtype: float64

In [112]:
crdata['person_income'].sort_values(ascending=False)

32297    6000000
30049    2039784
32546    1900000
32497    1782000
31924    1440000
          ...
15961       4800
15963       4200
27896       4200
15964       4080
31930       4000
Name: person_income, Length: 32581, dtype: int64

In [113]:
crdata.loc[(crdata['person_age']<70) & (crdata['person_income']<6000000),['person_age','person_income','person_emp_length','loan_amnt']].groupby(['person_age','person_income','person_emp_length'])['loan_amnt'].agg(
Total_Loan_Amount= 'sum')

                                            Total_Loan_Amount
person_age person_income person_emp_length
20         32652         0.0                             6000
           34800         3.0                             7000
           42000         4.0                             6500
           64000         3.0                            16000
           65000         4.0                             9600
...                                                       ...
67         200000        2.0                             3000
69         24000         3.0                            12000
           37000         6.0                            10750
           80000         12.0                            4800
           120000        3.0                            20000

[18545 rows x 1 columns]

In [114]:
# Filtering and selecting columns using .loc, then grouping
result = crdata.loc[
    (crdata['person_age'] > 70) & (crdata['person_income'] > 6000000), 
    ['person_age', 'person_income', 'person_emp_length', 'loan_amnt']
].groupby(['person_age', 'person_income', 'person_emp_length'])['loan_amnt'].agg(
    Total_Loan_Amount='sum'
).reset_index()

In [115]:
# Corrected Pandas syntax
result = crdata[
    (crdata['person_age'] <= 70) & (crdata['person_income'] <= 6000000)
].groupby(['person_age', 'person_income', 'person_emp_length'])['loan_amnt'].agg(
    Total_Loan_Amount='sum'
).reset_index()

In [116]:
result

       person_age  person_income  person_emp_length  Total_Loan_Amount
0              20          32652                0.0               6000
1              20          34800                3.0               7000
2              20          42000                4.0               6500
3              20          64000                3.0              16000
4              20          65000                4.0               9600
...           ...            ...                ...                ...
18546          70          30000                1.0               5000
18547          70          42000                1.0               8000
18548          70          44000                3.0               7000
18549          70          48000                0.0              15000
18550          70         132000                0.0              14000

[18551 rows x 4 columns]

In [117]:
crdata['missing_data']=crdata.isnull().sum()

In [118]:
crdata.shape

(32581, 13)

In [119]:
crdata.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,missing_data
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,NaN
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,NaN
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,NaN
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,NaN
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,NaN

In [120]:
crdata.drop(columns=['missing_data'],inplace=True)

In [121]:
crdata.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [122]:

threshold = 10

missing_percentage = (crdata.isnull().sum() / len(crdata)) * 100

columns_to_drop = missing_percentage[missing_percentage > threshold].index.tolist()

In [123]:
'''if columns_to_drop:
    print(f"Dropping columns: {columns_to_drop}")
    crdata = crdata.drop(columns=columns_to_drop)
else:
    print("No columns exceeded the missing data threshold.")'''

'if columns_to_drop:\n    print(f"Dropping columns: {columns_to_drop}")\n    crdata = crdata.drop(columns=columns_to_drop)\nelse:\n    print("No columns exceeded the missing data threshold.")'

In [124]:
columns_to_drop.count

In [125]:
crdata['loan_intent'].value_counts()

EDUCATION            6453
MEDICAL              6071
VENTURE              5719
PERSONAL             5521
DEBTCONSOLIDATION    5212
HOMEIMPROVEMENT      3605
Name: loan_intent, dtype: int64

In [126]:
crdata

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [127]:
crdata.pivot_table(index='person_home_ownership',values='person_income',aggfunc=
                   'count').sort_values(by='person_income', ascending=False)

                       person_income
person_home_ownership
RENT                           16446
MORTGAGE                       13444
OWN                             2584
OTHER                            107

In [128]:
crdata.pivot_table(index='person_age',columns='loan_status',values='loan_intent', aggfunc=
                    'count').reset_index().sort_values(by='person_age', ascending=False)

loan_status  person_age       0      1
57                  144     3.0    NaN
56                  123     2.0    NaN
55                   94     1.0    NaN
54                   84     1.0    NaN
53                   80     1.0    NaN
52                   78     1.0    NaN
51                   76     1.0    NaN
50                   73     3.0    NaN
49                   70     5.0    2.0
48                   69     5.0    NaN
47                   67     1.0    NaN
46                   66     6.0    3.0
45                   65     6.0    3.0
44                   64     6.0    1.0
43                   63     2.0    1.0
42                   62     4.0    3.0
41                   61     5.0    4.0
40                   60     8.0    7.0
39                   59     5.0    NaN
38                   58    16.0    3.0
37                   57    11.0    4.0
36                   56    14.0    1.0
35                   55    13.0    7.0
34                   54    17.0    7.0
33                   53    23.0    7.0
32                   52    24.0   12.0
31                   51    31.0    8.0
30                   50    40.0   12.0
29                   49    37.0   12.0
28                   48    55.0   20.0
27                   47    79.0   15.0
26                   46    82.0   12.0
25                   45    81.0   27.0
24                   44   114.0   27.0
23                   43   135.0   29.0
22                   42   138.0   50.0
21                   41   199.0   42.0
20                   40   214.0   57.0
19                   39   233.0   69.0
18                   38   311.0   62.0
17                   37   381.0   97.0
16                   36   425.0  123.0
15                   35   492.0  128.0
14                   34   570.0  139.0
13                   33   683.0  173.0
12                   32   771.0  193.0
11                   31   907.0  235.0
10                   30  1056.0  260.0
9                    29  1344.0  343.0
8                    28  1440.0  414.0
7                    27  1694.0  444.0
6                    26  1960.0  517.0
5                    25  2362.0  675.0
4                    24  2780.0  769.0
3                    23  3056.0  833.0
2                    22  2749.0  884.0
1                    21   857.0  372.0
0                    20    13.0    2.0

In [129]:
cleaned_df = crdata[crdata['person_age']<=70]

In [130]:
cr_age_remove.shape

NameError: name 'cr_age_remove' is not defined

In [ ]:
#cr_age_remove.pivot_table(index='person_emp_length', values='',aggfunc='count').reset_index().sort_values(by='person_emp_length', ascending=False)

In [ ]:
crdata['loan_status'].value_counts()

In [131]:
crdata.columns.to_list()

['person_age',
 'person_income',
 'person_home_ownership',
 'person_emp_length',
 'loan_intent',
 'loan_grade',
 'loan_amnt',
 'loan_int_rate',
 'loan_status',
 'loan_percent_income',
 'cb_person_default_on_file',
 'cb_person_cred_hist_length']

In [132]:
cleaned_df.shape

(32568, 12)

In [133]:
#rdata.drop(columns='person_age', inplace=True)

In [134]:
cleaned_df = cleaned_df[(cleaned_df['person_age']<=90) & (cleaned_df['person_emp_length']<=45)]

In [135]:
cleaned_df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31671.000000,3.167100e+04,31671.000000,31671.000000,28626.000000,31671.000000,31671.000000,31671.000000
mean,27.717754,6.649231e+04,4.780714,9660.637492,11.040070,0.215497,0.169621,5.804395
std,6.159859,5.277413e+04,4.028718,6334.716643,3.229507,0.411173,0.106275,4.048776
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.936600e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.480000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,38.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [136]:
cleaned_df.shape

(31671, 12)

In [137]:
cleaned_df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length                0
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3045
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [138]:
cleaned_df.fillna({'loan_int_rate':cleaned_df['loan_int_rate'].median()}, inplace=True)

In [139]:
cleaned_df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [140]:
cleaned_df.groupby('loan_status').count()['person_age']

loan_status
0    24846
1     6825
Name: person_age, dtype: int64

In [141]:
str(6823/(24842+6823)*100)+str('%')

'21.547449865782408%'

In [ ]:
cleaned_data.