In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sb

In [2]:
crdata = pd.read_csv(r"C:\Users\sabar\OneDrive\Documents\AI_ML\Credit Risk Analytics\Risk Dataset\credit_risk_dataset.csv")
ogdata = pd.read_csv(r"C:\Users\sabar\OneDrive\Documents\AI_ML\Credit Risk Analytics\Risk Dataset\credit_risk_dataset.csv")

In [3]:
crdata.shape

(32581, 12)

In [4]:
crdata_copy = crdata.copy()

In [5]:
crdata_copy.shape

(32581, 12)

In [6]:
crdata.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [7]:
missing_data = crdata.isnull().sum()
missing_data_pct = (missing_data/len(crdata))*100

In [8]:
missing_data_pct.round(2)

person_age                    0.00
person_income                 0.00
person_home_ownership         0.00
person_emp_length             2.75
loan_intent                   0.00
loan_grade                    0.00
loan_amnt                     0.00
loan_int_rate                 9.56
loan_status                   0.00
loan_percent_income           0.00
cb_person_default_on_file     0.00
cb_person_cred_hist_length    0.00
dtype: float64

In [9]:
crdata['person_income'].sort_values(ascending=False)

32297    6000000
30049    2039784
32546    1900000
32497    1782000
31924    1440000
          ...
15961       4800
15963       4200
27896       4200
15964       4080
31930       4000
Name: person_income, Length: 32581, dtype: int64

In [10]:
crdata.loc[(crdata['person_age']<70) & (crdata['person_income']<6000000),['person_age','person_income','person_emp_length','loan_amnt']].groupby(['person_age','person_income','person_emp_length'])['loan_amnt'].agg(
Total_Loan_Amount= 'sum')

                                            Total_Loan_Amount
person_age person_income person_emp_length
20         32652         0.0                             6000
           34800         3.0                             7000
           42000         4.0                             6500
           64000         3.0                            16000
           65000         4.0                             9600
...                                                       ...
67         200000        2.0                             3000
69         24000         3.0                            12000
           37000         6.0                            10750
           80000         12.0                            4800
           120000        3.0                            20000

[18545 rows x 1 columns]

In [11]:
# Filtering and selecting columns using .loc, then grouping
result = crdata.loc[
    (crdata['person_age'] > 70) & (crdata['person_income'] > 6000000), 
    ['person_age', 'person_income', 'person_emp_length', 'loan_amnt']
].groupby(['person_age', 'person_income', 'person_emp_length'])['loan_amnt'].agg(
    Total_Loan_Amount='sum'
).reset_index()

In [12]:
# Corrected Pandas syntax
result = crdata[
    (crdata['person_age'] <= 70) & (crdata['person_income'] <= 6000000)
].groupby(['person_age', 'person_income', 'person_emp_length'])['loan_amnt'].agg(
    Total_Loan_Amount='sum'
).reset_index()

In [13]:
result

       person_age  person_income  person_emp_length  Total_Loan_Amount
0              20          32652                0.0               6000
1              20          34800                3.0               7000
2              20          42000                4.0               6500
3              20          64000                3.0              16000
4              20          65000                4.0               9600
...           ...            ...                ...                ...
18546          70          30000                1.0               5000
18547          70          42000                1.0               8000
18548          70          44000                3.0               7000
18549          70          48000                0.0              15000
18550          70         132000                0.0              14000

[18551 rows x 4 columns]

In [14]:
crdata['missing_data']=crdata.isnull().sum()

In [15]:
crdata.shape

(32581, 13)

In [16]:
crdata.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,missing_data
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3,NaN
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2,NaN
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3,NaN
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2,NaN
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4,NaN

In [17]:
crdata.drop(columns=['missing_data'],inplace=True)

In [18]:
crdata.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [19]:

threshold = 10

missing_percentage = (crdata.isnull().sum() / len(crdata)) * 100

columns_to_drop = missing_percentage[missing_percentage > threshold].index.tolist()

In [20]:
'''if columns_to_drop:
    print(f"Dropping columns: {columns_to_drop}")
    crdata = crdata.drop(columns=columns_to_drop)
else:
    print("No columns exceeded the missing data threshold.")'''

'if columns_to_drop:\n    print(f"Dropping columns: {columns_to_drop}")\n    crdata = crdata.drop(columns=columns_to_drop)\nelse:\n    print("No columns exceeded the missing data threshold.")'

In [21]:
columns_to_drop.count

In [22]:
crdata['loan_intent'].value_counts()

EDUCATION            6453
MEDICAL              6071
VENTURE              5719
PERSONAL             5521
DEBTCONSOLIDATION    5212
HOMEIMPROVEMENT      3605
Name: loan_intent, dtype: int64

In [23]:
crdata

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [24]:
crdata.pivot_table(index='person_home_ownership',values='person_income',aggfunc=
                   'count').sort_values(by='person_income', ascending=False)

                       person_income
person_home_ownership
RENT                           16446
MORTGAGE                       13444
OWN                             2584
OTHER                            107

In [25]:
crdata.pivot_table(index='person_age',columns='loan_status',values='loan_intent', aggfunc=
                    'count').reset_index().sort_values(by='person_age', ascending=False)

loan_status  person_age       0      1
57                  144     3.0    NaN
56                  123     2.0    NaN
55                   94     1.0    NaN
54                   84     1.0    NaN
53                   80     1.0    NaN
52                   78     1.0    NaN
51                   76     1.0    NaN
50                   73     3.0    NaN
49                   70     5.0    2.0
48                   69     5.0    NaN
47                   67     1.0    NaN
46                   66     6.0    3.0
45                   65     6.0    3.0
44                   64     6.0    1.0
43                   63     2.0    1.0
42                   62     4.0    3.0
41                   61     5.0    4.0
40                   60     8.0    7.0
39                   59     5.0    NaN
38                   58    16.0    3.0
37                   57    11.0    4.0
36                   56    14.0    1.0
35                   55    13.0    7.0
34                   54    17.0    7.0
33                   53    23.0    7.0
32                   52    24.0   12.0
31                   51    31.0    8.0
30                   50    40.0   12.0
29                   49    37.0   12.0
28                   48    55.0   20.0
27                   47    79.0   15.0
26                   46    82.0   12.0
25                   45    81.0   27.0
24                   44   114.0   27.0
23                   43   135.0   29.0
22                   42   138.0   50.0
21                   41   199.0   42.0
20                   40   214.0   57.0
19                   39   233.0   69.0
18                   38   311.0   62.0
17                   37   381.0   97.0
16                   36   425.0  123.0
15                   35   492.0  128.0
14                   34   570.0  139.0
13                   33   683.0  173.0
12                   32   771.0  193.0
11                   31   907.0  235.0
10                   30  1056.0  260.0
9                    29  1344.0  343.0
8                    28  1440.0  414.0
7                    27  1694.0  444.0
6                    26  1960.0  517.0
5                    25  2362.0  675.0
4                    24  2780.0  769.0
3                    23  3056.0  833.0
2                    22  2749.0  884.0
1                    21   857.0  372.0
0                    20    13.0    2.0

In [26]:
cleaned_df = crdata[crdata['person_age']<=70]

In [27]:
'''cr_age_remove.pivot_table(index='person_emp_length', values='',aggfunc='count').reset_index().sort_values(by='person_emp_length', ascending=False)'''

"cr_age_remove.pivot_table(index='person_emp_length', values='',aggfunc='count').reset_index().sort_values(by='person_emp_length', ascending=False)"

In [28]:
crdata['loan_status'].value_counts()

0    25473
1     7108
Name: loan_status, dtype: int64

In [29]:
crdata.columns.to_list()

['person_age',
 'person_income',
 'person_home_ownership',
 'person_emp_length',
 'loan_intent',
 'loan_grade',
 'loan_amnt',
 'loan_int_rate',
 'loan_status',
 'loan_percent_income',
 'cb_person_default_on_file',
 'cb_person_cred_hist_length']

In [30]:
cleaned_df.shape

(32568, 12)

In [31]:
#rdata.drop(columns='person_age', inplace=True)

In [32]:
cleaned_df = cleaned_df[(cleaned_df['person_age']<=90) & (cleaned_df['person_emp_length']<=45)]

In [33]:
cleaned_df.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,31671.000000,3.167100e+04,31671.000000,31671.000000,28626.000000,31671.000000,31671.000000,31671.000000
mean,27.717754,6.649231e+04,4.780714,9660.637492,11.040070,0.215497,0.169621,5.804395
std,6.159859,5.277413e+04,4.028718,6334.716643,3.229507,0.411173,0.106275,4.048776
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.936600e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.600000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,8.000000e+04,7.000000,12500.000000,13.480000,0.000000,0.230000,8.000000
max,70.000000,2.039784e+06,38.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [34]:
cleaned_df.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length                0
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3045
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [35]:
cleaned_df.fillna({'loan_int_rate':cleaned_df['loan_int_rate'].median()}, inplace=True)

In [36]:
cleaned_df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [37]:
cleaned_df.groupby('loan_status').count()['person_age']

loan_status
0    24846
1     6825
Name: person_age, dtype: int64

In [38]:
str(6823/(24842+6823)*100)+str('%')

'21.547449865782408%'

In [39]:
cleaned_df_copy = cleaned_df.copy()

In [40]:
cleaned_df_copy.shape

(31671, 12)

In [41]:
cleaned_df.shape

(31671, 12)

In [42]:
cleaned_df.drop(columns='loan_grade',inplace=True)

In [43]:
cleaned_df.shape

(31671, 11)

In [44]:
cleaned_df.head(3)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
1,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2

In [45]:
cleaned_df.reset_index(drop=True, inplace=True)

In [46]:
cleaned_df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2
...,...,...,...,...,...,...,...,...,...,...,...
31666,57,53000,MORTGAGE,1.0,PERSONAL,5800,13.16,0,0.11,N,30
31667,54,120000,MORTGAGE,4.0,PERSONAL,17625,7.49,0,0.15,N,19
31668,65,76000,RENT,3.0,HOMEIMPROVEMENT,35000,10.99,1,0.46,N,28
31669,56,150000,MORTGAGE,5.0,PERSONAL,15000,11.48,0,0.10,N,26
31670,66,42000,RENT,2.0,MEDICAL,6475,9.99,0,0.15,N,30

#  Categorical Fetures Treatment

In [47]:
#One hot encoding

In [48]:
cleaned_df_cft = cleaned_df.copy()

In [49]:
person_home_ownership = pd.get_dummies(cleaned_df_cft['person_home_ownership'], drop_first=True).astype(int)
loan_intent = pd.get_dummies(cleaned_df_cft['loan_intent'],drop_first=True).astype(int)

In [50]:
person_home_ownership

       OTHER  OWN  RENT
0          0    1     0
1          0    0     0
2          0    0     1
3          0    0     1
4          0    1     0
...      ...  ...   ...
31666      0    0     0
31667      0    0     0
31668      0    0     1
31669      0    0     0
31670      0    0     1

[31671 rows x 3 columns]

In [51]:
loan_intent

       EDUCATION  HOMEIMPROVEMENT  MEDICAL  PERSONAL  VENTURE
0              1                0        0         0        0
1              0                0        1         0        0
2              0                0        1         0        0
3              0                0        1         0        0
4              0                0        0         0        1
...          ...              ...      ...       ...      ...
31666          0                0        0         1        0
31667          0                0        0         1        0
31668          0                1        0         0        0
31669          0                0        0         1        0
31670          0                0        1         0        0

[31671 rows x 5 columns]

In [52]:
# Binnary feeding

In [53]:
cb_person_default_on_binnary = np.where(cleaned_df_cft['cb_person_default_on_file']=='Y',1,0)
cb_person_default_on_binnary

array([0, 0, 0, ..., 0, 0, 0])

In [54]:
cleaned_df_cft.head(2)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3

In [55]:
cleaned_df_cft.drop(columns=['person_home_ownership','loan_intent','cb_person_default_on_file','loan_status'], inplace=True)

In [56]:
cleaned_df_cft

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
0,21,9600,5.0,1000,11.14,0.10,2
1,25,9600,1.0,5500,12.87,0.57,3
2,23,65500,4.0,35000,15.23,0.53,2
3,24,54400,8.0,35000,14.27,0.55,4
4,21,9900,2.0,2500,7.14,0.25,2
...,...,...,...,...,...,...,...
31666,57,53000,1.0,5800,13.16,0.11,30
31667,54,120000,4.0,17625,7.49,0.15,19
31668,65,76000,3.0,35000,10.99,0.46,28
31669,56,150000,5.0,15000,11.48,0.10,26
31670,66,42000,2.0,6475,9.99,0.15,30

# Scaling

In [57]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [58]:
data_to_scale = cleaned_df_cft.copy()

In [59]:
scaled_df = scaler.fit_transform(data_to_scale)

In [60]:
scaled_df

array([[-1.09058679, -1.07805103,  0.05443152, ...,  0.03411508,
        -0.655113  , -0.93965566],
       [-0.44121099, -1.07805103, -0.93845588, ...,  0.59757502,
         3.76746129, -0.69266353],
       [-0.76589889, -0.01880318, -0.19379033, ...,  1.36622557,
         3.39107199, -0.93965566],
       ...,
       [ 6.05254702,  0.18016109, -0.44201218, ..., -0.01473982,
         2.73239071,  5.48213962],
       [ 4.59145147,  1.58238543,  0.05443152, ...,  0.14485288,
        -0.655113  ,  4.98815537],
       [ 6.21489097, -0.46410415, -0.69023403, ..., -0.34043921,
        -0.18462637,  5.97612388]])

In [61]:
cleaned_df_cft.columns

Index(['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length'],
      dtype='object')

In [62]:
scaled_tran_df=pd.DataFrame(scaled_df, columns=['person_age', 'person_income', 'person_emp_length', 'loan_amnt',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length'])

In [63]:
scaled_tran_df

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656
...,...,...,...,...,...,...,...
31666,4.753795,-0.255665,-0.938456,-0.609451,0.692028,-0.561016,5.976124
31667,4.266764,1.013916,-0.193790,1.257276,-1.154688,-0.184626,3.259210
31668,6.052547,0.180161,-0.442012,4.000141,-0.014740,2.732391,5.482140
31669,4.591451,1.582385,0.054432,0.842886,0.144853,-0.655113,4.988155
31670,6.214891,-0.464104,-0.690234,-0.502893,-0.340439,-0.184626,5.976124

In [64]:
round(scaled_tran_df['person_age'].std(),2)

1.0

In [65]:
round(scaled_tran_df['person_income'].mean(),2)

-0.0

In [66]:
scaled_concat_df = pd.concat([scaled_tran_df,person_home_ownership,loan_intent],axis=1)

In [67]:
scaled_concat_df

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31666,4.753795,-0.255665,-0.938456,-0.609451,0.692028,-0.561016,5.976124,0,0,0,0,0,0,1,0
31667,4.266764,1.013916,-0.193790,1.257276,-1.154688,-0.184626,3.259210,0,0,0,0,0,0,1,0
31668,6.052547,0.180161,-0.442012,4.000141,-0.014740,2.732391,5.482140,0,0,1,0,1,0,0,0
31669,4.591451,1.582385,0.054432,0.842886,0.144853,-0.655113,4.988155,0,0,0,0,0,0,1,0
31670,6.214891,-0.464104,-0.690234,-0.502893,-0.340439,-0.184626,5.976124,0,0,1,0,0,1,0,0

In [68]:
scaled_concat_df['loan_status']=cleaned_df['loan_status']

In [69]:
scaled_concat_df['cb_person_default_on_file'] = np.where(cleaned_df['cb_person_default_on_file']=='Y',1,0)

In [70]:
scaled_concat_df

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,OTHER,OWN,RENT,EDUCATION,HOMEIMPROVEMENT,MEDICAL,PERSONAL,VENTURE,loan_status,cb_person_default_on_file
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,1,0
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,1,0
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31666,4.753795,-0.255665,-0.938456,-0.609451,0.692028,-0.561016,5.976124,0,0,0,0,0,0,1,0,0,0
31667,4.266764,1.013916,-0.193790,1.257276,-1.154688,-0.184626,3.259210,0,0,0,0,0,0,1,0,0,0
31668,6.052547,0.180161,-0.442012,4.000141,-0.014740,2.732391,5.482140,0,0,1,0,1,0,0,0,1,0
31669,4.591451,1.582385,0.054432,0.842886,0.144853,-0.655113,4.988155,0,0,0,0,0,0,1,0,0,0
31670,6.214891,-0.464104,-0.690234,-0.502893,-0.340439,-0.184626,5.976124,0,0,1,0,0,1,0,0,0,0

In [71]:
scaled_concat_df.columns = scaled_concat_df.columns.str.lower()

In [72]:
scaled_concat_df.groupby('loan_status')['education'].count()

loan_status
0    24846
1     6825
Name: education, dtype: int64

In [73]:
     round((6825/(6825+24846))*100,2)

21.55

# SMOTE - Synthetic Minority Oversampling Techinque

## KNN Techinque is used behind the SMOTE technique (K-Nearest Neighbhors)

In [74]:
%pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

Requirement already satisfied: imbalanced-learn in c:\users\sabar\anaconda3\lib\site-packages (0.12.4)
Requirement already satisfied: numpy>=1.17.3 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (1.21.5)
Requirement already satisfied: scipy>=1.5.0 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (1.9.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (1.0.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sabar\anaconda3\lib\site-packages (from imbalanced-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [75]:
scaled_smote_df = scaled_concat_df.copy()

In [76]:
target = scaled_concat_df['loan_status']
features = scaled_concat_df.drop(columns=['loan_status'], axis=1)

In [77]:
target.shape

(31671,)

In [78]:
features.shape

(31671, 16)

In [79]:
smote=SMOTE()

In [80]:
balanced_features, balanced_target = smote.fit_resample(features,target)

In [81]:
balanced_features.shape

(49692, 16)

In [82]:
balanced_target.shape

(49692,)

In [83]:
balanced_features

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,other,own,rent,education,homeimprovement,medical,personal,venture,cb_person_default_on_file
0,-1.090587,-1.078051,0.054432,-1.367192,0.034115,-0.655113,-0.939656,0,1,0,1,0,0,0,0,0
1,-0.441211,-1.078051,-0.938456,-0.656810,0.597575,3.767461,-0.692664,0,0,0,0,0,1,0,0,0
2,-0.765899,-0.018803,-0.193790,4.000141,1.366226,3.391072,-0.939656,0,0,1,0,0,1,0,0,0
3,-0.603555,-0.229137,0.799097,4.000141,1.053554,3.579267,-0.445671,0,0,1,0,0,1,0,0,1
4,-1.090587,-1.072366,-0.690234,-1.130398,-1.268682,0.756347,-0.939656,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49687,0.866120,-0.633162,-0.298224,-0.852085,-1.341879,-0.377794,-0.068657,0,0,1,0,1,0,0,0,0
49688,0.194543,3.048481,1.543763,4.000141,1.287417,-0.180679,0.511211,0,0,0,0,0,0,0,0,0
49689,-0.443730,-0.578974,-0.697936,0.642497,0.709801,1.981072,-0.692664,0,0,0,0,0,1,0,0,1
49690,-0.624177,-0.940261,-0.948966,-0.735741,1.019341,1.214881,-0.456130,0,0,1,1,0,0,0,0,1
49691,2.423514,-0.158546,2.332361,0.466740,0.024063,0.119733,2.365776,0,0,0,0,0,1,0,0,0

In [84]:
balanced_target

0        0
1        1
2        1
3        1
4        1
        ..
49687    1
49688    1
49689    1
49690    1
49691    1
Name: loan_status, Length: 49692, dtype: int64

In [85]:
scaled_smote_df.groupby('loan_status')['education'].count()

loan_status
0    24846
1     6825
Name: education, dtype: int64

In [86]:
balance_check = pd.DataFrame({'target':balanced_target})

In [87]:
balance_check.groupby('target').size()

target
0    24846
1    24846
dtype: int64

# Model Training

In [88]:
%pip install xgboost logisticregression

Requirement already satisfied: xgboost in c:\users\sabar\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: logisticregression in c:\users\sabar\anaconda3\lib\site-packages (2025.0.0)
Requirement already satisfied: numpy in c:\users\sabar\anaconda3\lib\site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in c:\users\sabar\anaconda3\lib\site-packages (from xgboost) (1.9.1)
Requirement already satisfied: pandas in c:\users\sabar\anaconda3\lib\site-packages (from logisticregression) (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\sabar\appdata\roaming\python\python39\site-packages (from pandas->logisticregression) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sabar\anaconda3\lib\site-packages (from pandas->logisticregression) (2022.1)
Requirement already satisfied: six>=1.5 in c:\users\sabar\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas->logisticregression) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [89]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [90]:
x_train, x_test, y_train, y_test = train_test_split(balanced_features,balanced_target, test_size=0.20, random_state=42)

In [91]:
x_train.shape

(39753, 16)

In [92]:
y_train.shape

(39753,)

In [93]:
x_test.shape

(9939, 16)

In [94]:
y_test.shape

(9939,)

In [95]:
logit = LogisticRegression()

In [96]:
logit.fit(x_train,y_train)

LogisticRegression()

In [97]:
logit.score(x_train, y_train)

0.7801675345256962

In [98]:
round((logit.score(x_test, y_test))*100,2)

77.88

In [99]:
logr_pred=logit.predict(x_test)

In [100]:
logr_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [101]:
print(classification_report(y_test,logr_pred))

              precision    recall  f1-score   support

           0       0.78      0.78      0.78      4995
           1       0.78      0.78      0.78      4944

    accuracy                           0.78      9939
   macro avg       0.78      0.78      0.78      9939
weighted avg       0.78      0.78      0.78      9939

In [102]:
print(logit.coef_)

[[-0.10104315  0.08307648 -0.03990212 -0.6714466   0.98687878  1.3962188
   0.04391652 -0.6913997  -2.14028387  0.45445564 -1.24395298 -0.31683453
  -0.54623696 -0.98995073 -1.52064473  0.07772344]]

In [103]:
feature_imp_logr =pd.DataFrame({'features_columns':balanced_features.columns, 'Coeff':logit.coef_[0]})

In [104]:
feature_imp_logr.sort_values(by='Coeff', ascending= False).reset_index()

    index            features_columns     Coeff
0       5         loan_percent_income  1.396219
1       4               loan_int_rate  0.986879
2       9                        rent  0.454456
3       1               person_income  0.083076
4      15   cb_person_default_on_file  0.077723
5       6  cb_person_cred_hist_length  0.043917
6       2           person_emp_length -0.039902
7       0                  person_age -0.101043
8      11             homeimprovement -0.316835
9      12                     medical -0.546237
10      3                   loan_amnt -0.671447
11      7                       other -0.691400
12     13                    personal -0.989951
13     10                   education -1.243953
14     14                     venture -1.520645
15      8                         own -2.140284

# XGBoost

In [105]:
%pip install xgboost

Requirement already satisfied: xgboost in c:\users\sabar\anaconda3\lib\site-packages (2.1.4)
Requirement already satisfied: numpy in c:\users\sabar\anaconda3\lib\site-packages (from xgboost) (1.21.5)
Requirement already satisfied: scipy in c:\users\sabar\anaconda3\lib\site-packages (from xgboost) (1.9.1)
Note: you may need to restart the kernel to use updated packages.

In [106]:
from xgboost import XGBClassifier

In [107]:
xgb = XGBClassifier()

In [108]:
xmodel=xgb.fit(x_train, y_train)

In [109]:
xpredict=xmodel.predict(x_test)

In [110]:
print(classification_report(y_test,xpredict))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95      4995
           1       0.98      0.91      0.94      4944

    accuracy                           0.94      9939
   macro avg       0.95      0.94      0.94      9939
weighted avg       0.95      0.94      0.94      9939

In [111]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [112]:
x_train, x_test, y_train,y_test= train_test_split(balanced_features,balanced_target, train_size=0.8, test_size=0.2, random_state=42)

In [113]:
logit = LogisticRegression()

In [114]:
c=logit.fit(x_train, y_train)

In [115]:
LR_Prediction=c.predict(x_test)

In [116]:
print(classification_report(y_test, LR_Prediction))

              precision    recall  f1-score   support

           0       0.78      0.78      0.78      4995
           1       0.78      0.78      0.78      4944

    accuracy                           0.78      9939
   macro avg       0.78      0.78      0.78      9939
weighted avg       0.78      0.78      0.78      9939

In [117]:
from xgboost import XGBClassifier

In [118]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8
)

In [119]:
xgb.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [120]:
XGB_Prediction=xgb.predict(x_test)

In [121]:
print(classification_report(y_test,XGB_Prediction))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      4995
           1       0.96      0.87      0.91      4944

    accuracy                           0.92      9939
   macro avg       0.92      0.92      0.92      9939
weighted avg       0.92      0.92      0.92      9939

In [122]:
dataframe = pd.DataFrame({'col':balanced_features.columns, 'coeff':logit.coef_[0]})
xgb_features =pd.DataFrame({'features_columns':balanced_features.columns, 'Coeff':logit.coef_[0]})

In [123]:
xgb_features.sort_values(by= 'Coeff', ascending=False).reset_index()

    index            features_columns     Coeff
0       5         loan_percent_income  1.396219
1       4               loan_int_rate  0.986879
2       9                        rent  0.454456
3       1               person_income  0.083076
4      15   cb_person_default_on_file  0.077723
5       6  cb_person_cred_hist_length  0.043917
6       2           person_emp_length -0.039902
7       0                  person_age -0.101043
8      11             homeimprovement -0.316835
9      12                     medical -0.546237
10      3                   loan_amnt -0.671447
11      7                       other -0.691400
12     13                    personal -0.989951
13     10                   education -1.243953
14     14                     venture -1.520645
15      8                         own -2.140284

In [124]:
dataframe

                           col     coeff
0                   person_age -0.101043
1                person_income  0.083076
2            person_emp_length -0.039902
3                    loan_amnt -0.671447
4                loan_int_rate  0.986879
5          loan_percent_income  1.396219
6   cb_person_cred_hist_length  0.043917
7                        other -0.691400
8                          own -2.140284
9                         rent  0.454456
10                   education -1.243953
11             homeimprovement -0.316835
12                     medical -0.546237
13                    personal -0.989951
14                     venture -1.520645
15   cb_person_default_on_file  0.077723

# Random Forest

In [125]:
from sklearn.ensemble import RandomForestClassifier

In [126]:
rf = RandomForestClassifier()

In [127]:
rf.fit(x_train, y_train)

RandomForestClassifier()

In [128]:
rf.score(x_train, y_train)

1.0

In [129]:
rf_prediction=rf.predict(x_test)

In [130]:
print(classification_report(y_test, rf_prediction))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94      4995
           1       0.97      0.91      0.94      4944

    accuracy                           0.94      9939
   macro avg       0.94      0.94      0.94      9939
weighted avg       0.94      0.94      0.94      9939

In [131]:
rf_coeff=rf.feature_importances_

In [132]:
rf_woe = pd.DataFrame({'RF_Featues':balanced_features.columns, 'Coeff':rf_coeff})

In [133]:
rf_woe.sort_values(by='Coeff', ascending=False).reset_index()

    index                  RF_Featues     Coeff
0       4               loan_int_rate  0.206870
1       5         loan_percent_income  0.195130
2       1               person_income  0.155698
3       3                   loan_amnt  0.083431
4       2           person_emp_length  0.074926
5       0                  person_age  0.062503
6       6  cb_person_cred_hist_length  0.060814
7       9                        rent  0.048062
8       8                         own  0.020370
9      15   cb_person_default_on_file  0.020112
10     14                     venture  0.017846
11     11             homeimprovement  0.016860
12     10                   education  0.015121
13     13                    personal  0.013176
14     12                     medical  0.008649
15      7                       other  0.000433

# XGBoost

In [134]:
from xgboost import XGBClassifier

In [135]:
X = XGBClassifier(tree_method='exact')

In [136]:
X.fit(x_train,y_train.values.ravel())

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [137]:
X.score(x_train,y_train.values.ravel())

0.9647825321359395

In [138]:
XGBPrediction = X.predict(x_test)

In [139]:
XGBPrediction

array([0, 0, 0, ..., 0, 0, 1])

In [140]:
print(classification_report(y_test,XGBPrediction))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95      4995
           1       0.98      0.91      0.95      4944

    accuracy                           0.95      9939
   macro avg       0.95      0.95      0.95      9939
weighted avg       0.95      0.95      0.95      9939

In [141]:
feature_importance = pd.concat([feature_imp_logr,rf_woe,xgb_features],axis=1)

In [142]:
feature_importance

,features_columns,Coeff,RF_Featues,Coeff,features_columns,Coeff
0,person_age,-0.101043,person_age,0.062503,person_age,-0.101043
1,person_income,0.083076,person_income,0.155698,person_income,0.083076
2,person_emp_length,-0.039902,person_emp_length,0.074926,person_emp_length,-0.039902
3,loan_amnt,-0.671447,loan_amnt,0.083431,loan_amnt,-0.671447
4,loan_int_rate,0.986879,loan_int_rate,0.206870,loan_int_rate,0.986879
5,loan_percent_income,1.396219,loan_percent_income,0.195130,loan_percent_income,1.396219
6,cb_person_cred_hist_length,0.043917,cb_person_cred_hist_length,0.060814,cb_person_cred_hist_length,0.043917
7,other,-0.691400,other,0.000433,other,-0.691400
8,own,-2.140284,own,0.020370,own,-2.140284
9,rent,0.454456,rent,0.048062,rent,0.454456
10,education,-1.243953,education,0.015121,education,-1.243953
11,homeimprovement,-0.316835,homeimprovement,0.016860,homeimprovement,-0.316835
12,medical,-0.546237,medical,0.008649,medical,-0.546237
13,personal,-0.989951,personal,0.013176,personal,-0.989951
14,venture,-1.520645,venture,0.017846,venture,-1.520645
15,cb_person_default_on_file,0.077723,cb_person_default_on_file,0.020112,cb_person_default_on_file,0.077723

# Further Exploration

In [143]:
xgb_prediction_df = pd.DataFrame({'xgb_test_index':x_test.index, 'xgb_prediction':XGBPrediction})
rf_prediction_df = pd.DataFrame({'rf_test_index': x_test.index, 'rf_prediction':rf_prediction})
logit_prediction_df = pd.DataFrame({'logit_test_index': x_test.index, 'logit_prediction':logr_pred})

In [144]:
xgb_prediction_df.head()
rf_prediction_df.head()
logit_prediction_df.head()

   logit_test_index  logit_prediction
0             24808                 0
1              9935                 0
2             14054                 0
3               147                 0
4              4070                 0

In [145]:
merge_with_xgb = cleaned_df.merge(xgb_prediction_df, left_index=True, right_on='xgb_test_index', how='left')
merge_with_xgb.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,xgb_test_index,xgb_prediction
NaN,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0,NaN
9831.0,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,1,1.0
NaN,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,2,NaN
NaN,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,3,NaN
442.0,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,4,1.0

In [146]:
merge_with_rf = merge_with_xgb.merge(rf_prediction_df, left_index=True, right_on='rf_test_index', how='left')
merge_final = merge_with_rf.merge(logit_prediction_df, left_index=True, right_on='logit_test_index', how= 'left')

In [147]:
merge_final.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,xgb_test_index,xgb_prediction,rf_test_index,rf_prediction,logit_test_index,logit_prediction
NaN,21,9600,OWN,5.0,EDUCATION,1000,11.14,0,0.10,N,2,0,NaN,NaN,NaN,NaN,NaN
NaN,25,9600,MORTGAGE,1.0,MEDICAL,5500,12.87,1,0.57,N,3,1,1.0,9831.0,NaN,NaN,NaN
NaN,23,65500,RENT,4.0,MEDICAL,35000,15.23,1,0.53,N,2,2,NaN,NaN,NaN,NaN,NaN
NaN,24,54400,RENT,8.0,MEDICAL,35000,14.27,1,0.55,Y,4,3,NaN,NaN,NaN,NaN,NaN
NaN,21,9900,OWN,2.0,VENTURE,2500,7.14,1,0.25,N,2,4,1.0,442.0,NaN,NaN,NaN

In [148]:
merge_final.shape

(31671, 17)

In [149]:
miss=(merge_final.isnull().sum()/len(merge_final))*100
miss

person_age                     0.000000
person_income                  0.000000
person_home_ownership          0.000000
person_emp_length              0.000000
loan_intent                    0.000000
loan_amnt                      0.000000
loan_int_rate                  0.000000
loan_status                    0.000000
loan_percent_income            0.000000
cb_person_default_on_file      0.000000
cb_person_cred_hist_length     0.000000
xgb_test_index                 0.000000
xgb_prediction                79.874333
rf_test_index                 79.874333
rf_prediction                 95.844779
logit_test_index              95.844779
logit_prediction              99.138013
dtype: float64

In [150]:
merge_final.dropna(inplace=True)

In [151]:
merge_final.shape

(273, 17)

In [152]:
merge_final.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,xgb_test_index,xgb_prediction,rf_test_index,rf_prediction,logit_test_index,logit_prediction
7782.0,24,78956,RENT,5.0,MEDICAL,35000,11.11,1,0.44,N,4,6,1.0,5893.0,0.0,8675.0,1.0
7968.0,25,12600,OWN,3.0,PERSONAL,1750,13.61,0,0.14,N,3,103,0.0,3308.0,1.0,3755.0,0.0
9251.0,22,153000,MORTGAGE,5.0,DEBTCONSOLIDATION,24000,15.62,1,0.16,Y,2,341,1.0,2116.0,1.0,2186.0,0.0
5662.0,22,16094,MORTGAGE,2.0,VENTURE,5500,7.14,1,0.34,N,3,351,1.0,3229.0,0.0,9057.0,1.0
143.0,21,18000,OWN,1.0,PERSONAL,2500,11.36,0,0.14,N,3,454,0.0,1442.0,1.0,9313.0,0.0

In [153]:
merge_final.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length,xgb_test_index,xgb_prediction,rf_test_index,rf_prediction,logit_test_index,logit_prediction
count,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000,273.000000
mean,28.054945,65043.040293,4.849817,10168.772894,11.098498,0.230769,0.174066,5.985348,16339.322344,0.186813,5164.813187,0.267399,5186.835165,0.399267
std,6.209627,33288.573333,4.100234,6333.440272,2.894470,0.422099,0.105052,4.445727,9099.019188,0.390477,2898.920823,0.443415,2934.194145,0.490647
min,21.000000,10080.000000,0.000000,1000.000000,5.420000,0.000000,0.020000,2.000000,6.000000,0.000000,6.000000,0.000000,1.000000,0.000000
25%,24.000000,43000.000000,2.000000,5600.000000,8.590000,0.000000,0.100000,3.000000,8454.000000,0.000000,2630.000000,0.000000,2494.000000,0.000000
50%,26.000000,59000.000000,4.000000,9700.000000,10.990000,0.000000,0.150000,4.000000,16307.000000,0.000000,5369.000000,0.000000,5548.000000,0.000000
75%,31.000000,80000.000000,7.000000,13000.000000,13.220000,0.000000,0.240000,8.000000,24492.000000,0.000000,7776.000000,1.000000,7557.000000,1.000000
max,58.000000,261800.000000,22.000000,35000.000000,19.030000,1.000000,0.710000,30.000000,31557.000000,1.000000,9936.000000,1.000000,9848.000000,1.000000

In [154]:
final_predictions = merge_final.drop(columns=['xgb_test_index','rf_test_index','logit_test_index'], axis=1)

In [155]:
final_predictions.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,xgb_prediction,rf_prediction,logit_prediction
7782.0,24,78956,RENT,5.0,MEDICAL,35000,11.11,1,0.44,N,4,1.0,0.0,1.0
7968.0,25,12600,OWN,3.0,PERSONAL,1750,13.61,0,0.14,N,3,0.0,1.0,0.0
9251.0,22,153000,MORTGAGE,5.0,DEBTCONSOLIDATION,24000,15.62,1,0.16,Y,2,1.0,1.0,0.0
5662.0,22,16094,MORTGAGE,2.0,VENTURE,5500,7.14,1,0.34,N,3,1.0,0.0,1.0
143.0,21,18000,OWN,1.0,PERSONAL,2500,11.36,0,0.14,N,3,0.0,1.0,0.0

In [156]:
#final_predictions.to_excel(r'C:\Users\sabar\OneDrive\Documents\AI_ML\Credit Risk Analytics\pd_predictions.xlsx',index=False)

In [157]:
from sklearn.metrics import confusion_matrix

In [158]:
ConfusionMatrix = confusion_matrix

In [159]:
ConfusionMatrix(merge_final['loan_status'],merge_final['xgb_prediction'])

array([[204,   6],
       [ 18,  45]], dtype=int64)

In [160]:
merge_final.columns

Index(['person_age', 'person_income', 'person_home_ownership',
       'person_emp_length', 'loan_intent', 'loan_amnt', 'loan_int_rate',
       'loan_status', 'loan_percent_income', 'cb_person_default_on_file',
       'cb_person_cred_hist_length', 'xgb_test_index', 'xgb_prediction',
       'rf_test_index', 'rf_prediction', 'logit_test_index',
       'logit_prediction'],
      dtype='object')

In [161]:
print('-----------------END------------------')

-----------------END------------------